// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthSuccessOk.
const (
	True AuthSuccessOk = true
)

// Valid indicates whether the value is a known member of the AuthSuccessOk enum.
func (e AuthSuccessOk) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for BadRequestErrorCode.
const (
	CONTACTREQUIRED     BadRequestErrorCode = "CONTACT_REQUIRED"
	SLOTMISALIGNED      BadRequestErrorCode = "SLOT_MISALIGNED"
	SLOTOUTOFWINDOW     BadRequestErrorCode = "SLOT_OUT_OF_WINDOW"
	SLOTOUTSIDESCHEDULE BadRequestErrorCode = "SLOT_OUTSIDE_SCHEDULE"
	VALIDATIONERROR     BadRequestErrorCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the BadRequestErrorCode enum.
func (e BadRequestErrorCode) Valid() bool {
	switch e {
	case CONTACTREQUIRED:
		return true
	case SLOTMISALIGNED:
		return true
	case SLOTOUTOFWINDOW:
		return true
	case SLOTOUTSIDESCHEDULE:
		return true
	case VALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for ConflictErrorCode.
const (
	DUPLICATEEVENTTYPEID ConflictErrorCode = "DUPLICATE_EVENT_TYPE_ID"
	SLOTBUSY             ConflictErrorCode = "SLOT_BUSY"
)

// Valid indicates whether the value is a known member of the ConflictErrorCode enum.
func (e ConflictErrorCode) Valid() bool {
	switch e {
	case DUPLICATEEVENTTYPEID:
		return true
	case SLOTBUSY:
		return true
	default:
		return false
	}
}

// Defines values for GuestUnknownErrorCode.
const (
	GUESTUNKNOWN GuestUnknownErrorCode = "GUEST_UNKNOWN"
)

// Valid indicates whether the value is a known member of the GuestUnknownErrorCode enum.
func (e GuestUnknownErrorCode) Valid() bool {
	switch e {
	case GUESTUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for LoginThrottledErrorCode.
const (
	LOGINATTEMPTSEXCEEDED LoginThrottledErrorCode = "LOGIN_ATTEMPTS_EXCEEDED"
)

// Valid indicates whether the value is a known member of the LoginThrottledErrorCode enum.
func (e LoginThrottledErrorCode) Valid() bool {
	switch e {
	case LOGINATTEMPTSEXCEEDED:
		return true
	default:
		return false
	}
}

// Defines values for NotFoundErrorCode.
const (
	EVENTTYPENOTFOUND NotFoundErrorCode = "EVENT_TYPE_NOT_FOUND"
)

// Valid indicates whether the value is a known member of the NotFoundErrorCode enum.
func (e NotFoundErrorCode) Valid() bool {
	switch e {
	case EVENTTYPENOTFOUND:
		return true
	default:
		return false
	}
}

// Defines values for UnauthorizedErrorCode.
const (
	INVALIDCREDENTIALS UnauthorizedErrorCode = "INVALID_CREDENTIALS"
	NOOWNERSESSION     UnauthorizedErrorCode = "NO_OWNER_SESSION"
)

// Valid indicates whether the value is a known member of the UnauthorizedErrorCode enum.
func (e UnauthorizedErrorCode) Valid() bool {
	switch e {
	case INVALIDCREDENTIALS:
		return true
	case NOOWNERSESSION:
		return true
	default:
		return false
	}
}

// AuthSuccess Успешный вход: сессия выдаётся через httpOnly cookie `owner_session`.
type AuthSuccess struct {
	Ok AuthSuccessOk `json:"ok"`
}

// AuthSuccessOk defines model for AuthSuccess.Ok.
type AuthSuccessOk bool

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	Code    BadRequestErrorCode `json:"code"`
	Message string              `json:"message"`
}

// BadRequestErrorCode defines model for BadRequestError.Code.
type BadRequestErrorCode string

// Booking Бронирование.
type Booking struct {
	CreatedAt time.Time `json:"createdAt"`
	EndsAt    time.Time `json:"endsAt"`

	// EventType Снимок типа события на момент бронирования. Хранится даже после удаления типа.
	EventType    BookingEventType   `json:"eventType"`
	GuestComment *string            `json:"guestComment,omitempty"`
	GuestEmail   *string            `json:"guestEmail,omitempty"`
	GuestName    string             `json:"guestName"`
	GuestPhone   *string            `json:"guestPhone,omitempty"`
	Id           openapi_types.UUID `json:"id"`
	StartsAt     time.Time          `json:"startsAt"`
}

// BookingCreate Данные для создания бронирования.
type BookingCreate struct {
	// EventTypeId id (slug) выбранного типа события.
	EventTypeId  string  `json:"eventTypeId"`
	GuestComment *string `json:"guestComment,omitempty"`

	// GuestEmail Email гостя. Обязателен хотя бы один контакт: guestPhone или guestEmail.
	GuestEmail *openapi_types.Email `json:"guestEmail,omitempty"`
	GuestName  string               `json:"guestName"`

	// GuestPhone Телефон гостя. Обязателен хотя бы один контакт: guestPhone или guestEmail.
	GuestPhone *string `json:"guestPhone,omitempty"`

	// StartsAt Начало слота, ISO 8601 UTC. Кратно 15 минутам и внутри окна записи.
	StartsAt time.Time `json:"startsAt"`
}

// BookingEventType Снимок типа события на момент бронирования. Хранится даже после удаления типа.
type BookingEventType struct {
	DurationMinutes int32  `json:"durationMinutes"`
	Id              string `json:"id"`
	Title           string `json:"title"`
}

// ConflictError defines model for ConflictError.
type ConflictError struct {
	Code    ConflictErrorCode `json:"code"`
	Message string            `json:"message"`
}

// ConflictErrorCode defines model for ConflictError.Code.
type ConflictErrorCode string

// EventType Тип события — вид брони, который публикует владелец календаря.
type EventType struct {
	// Availability Собственное расписание доступности. Если не задано — используется
	// расписание владельца по умолчанию (GET/PUT /schedule).
	Availability *WeeklySchedule `json:"availability,omitempty"`

	// Description Описание для страницы выбора вида брони.
	Description string `json:"description"`

	// DurationMinutes Длительность встречи в минутах, кратна сетке слотов (15 минут).
	DurationMinutes int32 `json:"durationMinutes"`

	// Id Уникальный идентификатор (slug), задаётся владельцем при создании. Пример: "intro-call".
	Id string `json:"id"`

	// Title Название, отображается гостю. Пример: "Знакомственный звонок".
	Title string `json:"title"`
}

// GuestCreate Данные для создания/идентификации гостя.
type GuestCreate struct {
	// GuestEmail Email гостя.
	GuestEmail *openapi_types.Email `json:"guestEmail,omitempty"`

	// GuestPhone Телефон гостя.
	GuestPhone *string `json:"guestPhone,omitempty"`

	// Name Имя гостя.
	Name string `json:"name"`

	// RememberMe Запомнить гостя на 30 дней (cookie `guest_id` со сроком 30 дней).
	RememberMe bool `json:"rememberMe"`
}

// GuestProfile Профиль гостя, идентифицируемый по httpOnly cookie `guest_id`.
type GuestProfile struct {
	// GuestEmail Email гостя.
	GuestEmail *openapi_types.Email `json:"guestEmail,omitempty"`

	// GuestPhone Телефон гостя.
	GuestPhone *string `json:"guestPhone,omitempty"`

	// Id Идентификатор гостя (совпадает с cookie `guest_id`).
	Id string `json:"id"`

	// Name Имя гостя.
	Name string `json:"name"`
}

// GuestUnknownError defines model for GuestUnknownError.
type GuestUnknownError struct {
	Code    GuestUnknownErrorCode `json:"code"`
	Message string                `json:"message"`
}

// GuestUnknownErrorCode defines model for GuestUnknownError.Code.
type GuestUnknownErrorCode string

// LoginThrottledError defines model for LoginThrottledError.
type LoginThrottledError struct {
	Code    LoginThrottledErrorCode `json:"code"`
	Message string                  `json:"message"`
}

// LoginThrottledErrorCode defines model for LoginThrottledError.Code.
type LoginThrottledErrorCode string

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	Code    NotFoundErrorCode `json:"code"`
	Message string            `json:"message"`
}

// NotFoundErrorCode defines model for NotFoundError.Code.
type NotFoundErrorCode string

// OwnerLogin Данные для входа владельца.
type OwnerLogin struct {
	// Login Логин владельца, задан статически при старте сервера.
	Login string `json:"login"`

	// Password Пароль владельца, задан статически при старте сервера.
	Password string `json:"password"`
}

// Slot Свободный слот длиной в длительность типа события.
type Slot struct {
	EndsAt   time.Time `json:"endsAt"`
	StartsAt time.Time `json:"startsAt"`
}

// SlotsResponse Ответ со свободными слотами на окно записи.
type SlotsResponse struct {
	// Slots Свободные слоты по возрастанию startsAt.
	Slots []Slot `json:"slots"`

	// WindowEndsOn Последний день окна записи (14 дней, включая сегодняшний).
	WindowEndsOn openapi_types.Date `json:"windowEndsOn"`

	// WindowStartsOn Первый день окна записи — сегодня (UTC).
	WindowStartsOn openapi_types.Date `json:"windowStartsOn"`
}

// TimeInterval Интервал рабочего времени внутри дня, например 09:00–13:00.
type TimeInterval struct {
	// End Конец интервала, формат HH:mm. Должен быть больше начала.
	End string `json:"end"`

	// Start Начало интервала, формат HH:mm.
	Start string `json:"start"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Code    UnauthorizedErrorCode `json:"code"`
	Message string                `json:"message"`
}

// UnauthorizedErrorCode defines model for UnauthorizedError.Code.
type UnauthorizedErrorCode string

// WeeklySchedule Недельное расписание. Пустой массив интервалов — день недоступен.
type WeeklySchedule struct {
	// Fri Пятница.
	Fri []TimeInterval `json:"fri"`

	// Mon Понедельник.
	Mon []TimeInterval `json:"mon"`

	// Sat Суббота.
	Sat []TimeInterval `json:"sat"`

	// Sun Воскресенье.
	Sun []TimeInterval `json:"sun"`

	// Thu Четверг.
	Thu []TimeInterval `json:"thu"`

	// Tue Вторник.
	Tue []TimeInterval `json:"tue"`

	// Wed Среда.
	Wed []TimeInterval `json:"wed"`
}

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = OwnerLogin

// BookingsCreateJSONRequestBody defines body for BookingsCreate for application/json ContentType.
type BookingsCreateJSONRequestBody = BookingCreate

// EventTypesCreateJSONRequestBody defines body for EventTypesCreate for application/json ContentType.
type EventTypesCreateJSONRequestBody = EventType

// EventTypesUpdateJSONRequestBody defines body for EventTypesUpdate for application/json ContentType.
type EventTypesUpdateJSONRequestBody = EventType

// GuestCreateJSONRequestBody defines body for GuestCreate for application/json ContentType.
type GuestCreateJSONRequestBody = GuestCreate

// GuestUpdateJSONRequestBody defines body for GuestUpdate for application/json ContentType.
type GuestUpdateJSONRequestBody = GuestProfile

// ScheduleUpdateJSONRequestBody defines body for ScheduleUpdate for application/json ContentType.
type ScheduleUpdateJSONRequestBody = WeeklySchedule

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	AuthLogin(w http.ResponseWriter, r *http.Request)

	// (GET /bookings)
	BookingsList(w http.ResponseWriter, r *http.Request)

	// (POST /bookings)
	BookingsCreate(w http.ResponseWriter, r *http.Request)

	// (GET /event-types)
	EventTypesList(w http.ResponseWriter, r *http.Request)

	// (POST /event-types)
	EventTypesCreate(w http.ResponseWriter, r *http.Request)

	// (DELETE /event-types/{eventTypeId})
	EventTypesDelete(w http.ResponseWriter, r *http.Request, eventTypeId string)

	// (GET /event-types/{eventTypeId})
	EventTypesGet(w http.ResponseWriter, r *http.Request, eventTypeId string)

	// (PUT /event-types/{eventTypeId})
	EventTypesUpdate(w http.ResponseWriter, r *http.Request, eventTypeId string)

	// (GET /event-types/{eventTypeId}/slots)
	EventTypesListSlots(w http.ResponseWriter, r *http.Request, eventTypeId string)

	// (GET /guest)
	GuestGet(w http.ResponseWriter, r *http.Request)

	// (POST /guest)
	GuestCreate(w http.ResponseWriter, r *http.Request)

	// (PUT /guest)
	GuestUpdate(w http.ResponseWriter, r *http.Request)

	// (GET /schedule)
	ScheduleGet(w http.ResponseWriter, r *http.Request)

	// (PUT /schedule)
	ScheduleUpdate(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/login)
func (_ Unimplemented) AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /bookings)
func (_ Unimplemented) BookingsList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /bookings)
func (_ Unimplemented) BookingsCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /event-types)
func (_ Unimplemented) EventTypesList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /event-types)
func (_ Unimplemented) EventTypesCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /event-types/{eventTypeId})
func (_ Unimplemented) EventTypesDelete(w http.ResponseWriter, r *http.Request, eventTypeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /event-types/{eventTypeId})
func (_ Unimplemented) EventTypesGet(w http.ResponseWriter, r *http.Request, eventTypeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /event-types/{eventTypeId})
func (_ Unimplemented) EventTypesUpdate(w http.ResponseWriter, r *http.Request, eventTypeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /event-types/{eventTypeId}/slots)
func (_ Unimplemented) EventTypesListSlots(w http.ResponseWriter, r *http.Request, eventTypeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /guest)
func (_ Unimplemented) GuestGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /guest)
func (_ Unimplemented) GuestCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /guest)
func (_ Unimplemented) GuestUpdate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /schedule)
func (_ Unimplemented) ScheduleGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /schedule)
func (_ Unimplemented) ScheduleUpdate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BookingsList operation middleware
func (siw *ServerInterfaceWrapper) BookingsList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BookingsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BookingsCreate operation middleware
func (siw *ServerInterfaceWrapper) BookingsCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BookingsCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EventTypesList operation middleware
func (siw *ServerInterfaceWrapper) EventTypesList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EventTypesList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EventTypesCreate operation middleware
func (siw *ServerInterfaceWrapper) EventTypesCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EventTypesCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EventTypesDelete operation middleware
func (siw *ServerInterfaceWrapper) EventTypesDelete(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventTypeId" -------------
	var eventTypeId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventTypeId", chi.URLParam(r, "eventTypeId"), &eventTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventTypeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EventTypesDelete(w, r, eventTypeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EventTypesGet operation middleware
func (siw *ServerInterfaceWrapper) EventTypesGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventTypeId" -------------
	var eventTypeId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventTypeId", chi.URLParam(r, "eventTypeId"), &eventTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventTypeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EventTypesGet(w, r, eventTypeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EventTypesUpdate operation middleware
func (siw *ServerInterfaceWrapper) EventTypesUpdate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventTypeId" -------------
	var eventTypeId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventTypeId", chi.URLParam(r, "eventTypeId"), &eventTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventTypeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EventTypesUpdate(w, r, eventTypeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EventTypesListSlots operation middleware
func (siw *ServerInterfaceWrapper) EventTypesListSlots(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventTypeId" -------------
	var eventTypeId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventTypeId", chi.URLParam(r, "eventTypeId"), &eventTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventTypeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EventTypesListSlots(w, r, eventTypeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GuestGet operation middleware
func (siw *ServerInterfaceWrapper) GuestGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GuestGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GuestCreate operation middleware
func (siw *ServerInterfaceWrapper) GuestCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GuestCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GuestUpdate operation middleware
func (siw *ServerInterfaceWrapper) GuestUpdate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GuestUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScheduleGet operation middleware
func (siw *ServerInterfaceWrapper) ScheduleGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScheduleGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScheduleUpdate operation middleware
func (siw *ServerInterfaceWrapper) ScheduleUpdate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScheduleUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings", wrapper.BookingsList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings", wrapper.BookingsCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event-types", wrapper.EventTypesList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/event-types", wrapper.EventTypesCreate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/event-types/{eventTypeId}", wrapper.EventTypesDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event-types/{eventTypeId}", wrapper.EventTypesGet)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/event-types/{eventTypeId}", wrapper.EventTypesUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event-types/{eventTypeId}/slots", wrapper.EventTypesListSlots)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/guest", wrapper.GuestGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/guest", wrapper.GuestCreate)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/guest", wrapper.GuestUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/schedule", wrapper.ScheduleGet)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/schedule", wrapper.ScheduleUpdate)
	})

	return r
}

type AuthLoginRequestObject struct {
	Body *AuthLoginJSONRequestBody
}

type AuthLoginResponseObject interface {
	VisitAuthLoginResponse(w http.ResponseWriter) error
}

type AuthLogin200ResponseHeaders struct {
	SetCookie string
}

type AuthLogin200JSONResponse struct {
	Body    AuthSuccess
	Headers AuthLogin200ResponseHeaders
}

func (response AuthLogin200JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthLogin401JSONResponse UnauthorizedError

func (response AuthLogin401JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthLogin429JSONResponse LoginThrottledError

func (response AuthLogin429JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsListRequestObject struct {
}

type BookingsListResponseObject interface {
	VisitBookingsListResponse(w http.ResponseWriter) error
}

type BookingsList200JSONResponse []Booking

func (response BookingsList200JSONResponse) VisitBookingsListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsList401JSONResponse UnauthorizedError

func (response BookingsList401JSONResponse) VisitBookingsListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsCreateRequestObject struct {
	Body *BookingsCreateJSONRequestBody
}

type BookingsCreateResponseObject interface {
	VisitBookingsCreateResponse(w http.ResponseWriter) error
}

type BookingsCreate201JSONResponse Booking

func (response BookingsCreate201JSONResponse) VisitBookingsCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsCreate400JSONResponse BadRequestError

func (response BookingsCreate400JSONResponse) VisitBookingsCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsCreate404JSONResponse NotFoundError

func (response BookingsCreate404JSONResponse) VisitBookingsCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsCreate409JSONResponse ConflictError

func (response BookingsCreate409JSONResponse) VisitBookingsCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesListRequestObject struct {
}

type EventTypesListResponseObject interface {
	VisitEventTypesListResponse(w http.ResponseWriter) error
}

type EventTypesList200JSONResponse []EventType

func (response EventTypesList200JSONResponse) VisitEventTypesListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesCreateRequestObject struct {
	Body *EventTypesCreateJSONRequestBody
}

type EventTypesCreateResponseObject interface {
	VisitEventTypesCreateResponse(w http.ResponseWriter) error
}

type EventTypesCreate201JSONResponse EventType

func (response EventTypesCreate201JSONResponse) VisitEventTypesCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesCreate400JSONResponse BadRequestError

func (response EventTypesCreate400JSONResponse) VisitEventTypesCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesCreate401JSONResponse UnauthorizedError

func (response EventTypesCreate401JSONResponse) VisitEventTypesCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesCreate409JSONResponse ConflictError

func (response EventTypesCreate409JSONResponse) VisitEventTypesCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesDeleteRequestObject struct {
	EventTypeId string `json:"eventTypeId"`
}

type EventTypesDeleteResponseObject interface {
	VisitEventTypesDeleteResponse(w http.ResponseWriter) error
}

type EventTypesDelete204Response struct {
}

func (response EventTypesDelete204Response) VisitEventTypesDeleteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type EventTypesDelete401JSONResponse UnauthorizedError

func (response EventTypesDelete401JSONResponse) VisitEventTypesDeleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesDelete404JSONResponse NotFoundError

func (response EventTypesDelete404JSONResponse) VisitEventTypesDeleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesGetRequestObject struct {
	EventTypeId string `json:"eventTypeId"`
}

type EventTypesGetResponseObject interface {
	VisitEventTypesGetResponse(w http.ResponseWriter) error
}

type EventTypesGet200JSONResponse EventType

func (response EventTypesGet200JSONResponse) VisitEventTypesGetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesGet404JSONResponse NotFoundError

func (response EventTypesGet404JSONResponse) VisitEventTypesGetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesUpdateRequestObject struct {
	EventTypeId string `json:"eventTypeId"`
	Body        *EventTypesUpdateJSONRequestBody
}

type EventTypesUpdateResponseObject interface {
	VisitEventTypesUpdateResponse(w http.ResponseWriter) error
}

type EventTypesUpdate200JSONResponse EventType

func (response EventTypesUpdate200JSONResponse) VisitEventTypesUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesUpdate400JSONResponse BadRequestError

func (response EventTypesUpdate400JSONResponse) VisitEventTypesUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesUpdate401JSONResponse UnauthorizedError

func (response EventTypesUpdate401JSONResponse) VisitEventTypesUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesUpdate404JSONResponse NotFoundError

func (response EventTypesUpdate404JSONResponse) VisitEventTypesUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesListSlotsRequestObject struct {
	EventTypeId string `json:"eventTypeId"`
}

type EventTypesListSlotsResponseObject interface {
	VisitEventTypesListSlotsResponse(w http.ResponseWriter) error
}

type EventTypesListSlots200JSONResponse SlotsResponse

func (response EventTypesListSlots200JSONResponse) VisitEventTypesListSlotsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesListSlots404JSONResponse NotFoundError

func (response EventTypesListSlots404JSONResponse) VisitEventTypesListSlotsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GuestGetRequestObject struct {
}

type GuestGetResponseObject interface {
	VisitGuestGetResponse(w http.ResponseWriter) error
}

type GuestGet200JSONResponse GuestProfile

func (response GuestGet200JSONResponse) VisitGuestGetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GuestGet404JSONResponse GuestUnknownError

func (response GuestGet404JSONResponse) VisitGuestGetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GuestCreateRequestObject struct {
	Body *GuestCreateJSONRequestBody
}

type GuestCreateResponseObject interface {
	VisitGuestCreateResponse(w http.ResponseWriter) error
}

type GuestCreate201ResponseHeaders struct {
	SetCookie string
}

type GuestCreate201JSONResponse struct {
	Body    GuestProfile
	Headers GuestCreate201ResponseHeaders
}

func (response GuestCreate201JSONResponse) VisitGuestCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type GuestCreate400JSONResponse BadRequestError

func (response GuestCreate400JSONResponse) VisitGuestCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GuestCreate404JSONResponse GuestUnknownError

func (response GuestCreate404JSONResponse) VisitGuestCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GuestUpdateRequestObject struct {
	Body *GuestUpdateJSONRequestBody
}

type GuestUpdateResponseObject interface {
	VisitGuestUpdateResponse(w http.ResponseWriter) error
}

type GuestUpdate200JSONResponse GuestProfile

func (response GuestUpdate200JSONResponse) VisitGuestUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GuestUpdate400JSONResponse BadRequestError

func (response GuestUpdate400JSONResponse) VisitGuestUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GuestUpdate404JSONResponse GuestUnknownError

func (response GuestUpdate404JSONResponse) VisitGuestUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleGetRequestObject struct {
}

type ScheduleGetResponseObject interface {
	VisitScheduleGetResponse(w http.ResponseWriter) error
}

type ScheduleGet200JSONResponse WeeklySchedule

func (response ScheduleGet200JSONResponse) VisitScheduleGetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleGet401JSONResponse UnauthorizedError

func (response ScheduleGet401JSONResponse) VisitScheduleGetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleUpdateRequestObject struct {
	Body *ScheduleUpdateJSONRequestBody
}

type ScheduleUpdateResponseObject interface {
	VisitScheduleUpdateResponse(w http.ResponseWriter) error
}

type ScheduleUpdate200JSONResponse WeeklySchedule

func (response ScheduleUpdate200JSONResponse) VisitScheduleUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleUpdate400JSONResponse BadRequestError

func (response ScheduleUpdate400JSONResponse) VisitScheduleUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleUpdate401JSONResponse UnauthorizedError

func (response ScheduleUpdate401JSONResponse) VisitScheduleUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/login)
	AuthLogin(ctx context.Context, request AuthLoginRequestObject) (AuthLoginResponseObject, error)

	// (GET /bookings)
	BookingsList(ctx context.Context, request BookingsListRequestObject) (BookingsListResponseObject, error)

	// (POST /bookings)
	BookingsCreate(ctx context.Context, request BookingsCreateRequestObject) (BookingsCreateResponseObject, error)

	// (GET /event-types)
	EventTypesList(ctx context.Context, request EventTypesListRequestObject) (EventTypesListResponseObject, error)

	// (POST /event-types)
	EventTypesCreate(ctx context.Context, request EventTypesCreateRequestObject) (EventTypesCreateResponseObject, error)

	// (DELETE /event-types/{eventTypeId})
	EventTypesDelete(ctx context.Context, request EventTypesDeleteRequestObject) (EventTypesDeleteResponseObject, error)

	// (GET /event-types/{eventTypeId})
	EventTypesGet(ctx context.Context, request EventTypesGetRequestObject) (EventTypesGetResponseObject, error)

	// (PUT /event-types/{eventTypeId})
	EventTypesUpdate(ctx context.Context, request EventTypesUpdateRequestObject) (EventTypesUpdateResponseObject, error)

	// (GET /event-types/{eventTypeId}/slots)
	EventTypesListSlots(ctx context.Context, request EventTypesListSlotsRequestObject) (EventTypesListSlotsResponseObject, error)

	// (GET /guest)
	GuestGet(ctx context.Context, request GuestGetRequestObject) (GuestGetResponseObject, error)

	// (POST /guest)
	GuestCreate(ctx context.Context, request GuestCreateRequestObject) (GuestCreateResponseObject, error)

	// (PUT /guest)
	GuestUpdate(ctx context.Context, request GuestUpdateRequestObject) (GuestUpdateResponseObject, error)

	// (GET /schedule)
	ScheduleGet(ctx context.Context, request ScheduleGetRequestObject) (ScheduleGetResponseObject, error)

	// (PUT /schedule)
	ScheduleUpdate(ctx context.Context, request ScheduleUpdateRequestObject) (ScheduleUpdateResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AuthLogin operation middleware
func (sh *strictHandler) AuthLogin(w http.ResponseWriter, r *http.Request) {
	var request AuthLoginRequestObject

	var body AuthLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthLogin(ctx, request.(AuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthLoginResponseObject); ok {
		if err := validResponse.VisitAuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BookingsList operation middleware
func (sh *strictHandler) BookingsList(w http.ResponseWriter, r *http.Request) {
	var request BookingsListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BookingsList(ctx, request.(BookingsListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BookingsList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BookingsListResponseObject); ok {
		if err := validResponse.VisitBookingsListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BookingsCreate operation middleware
func (sh *strictHandler) BookingsCreate(w http.ResponseWriter, r *http.Request) {
	var request BookingsCreateRequestObject

	var body BookingsCreateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BookingsCreate(ctx, request.(BookingsCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BookingsCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BookingsCreateResponseObject); ok {
		if err := validResponse.VisitBookingsCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EventTypesList operation middleware
func (sh *strictHandler) EventTypesList(w http.ResponseWriter, r *http.Request) {
	var request EventTypesListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EventTypesList(ctx, request.(EventTypesListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventTypesList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EventTypesListResponseObject); ok {
		if err := validResponse.VisitEventTypesListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EventTypesCreate operation middleware
func (sh *strictHandler) EventTypesCreate(w http.ResponseWriter, r *http.Request) {
	var request EventTypesCreateRequestObject

	var body EventTypesCreateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EventTypesCreate(ctx, request.(EventTypesCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventTypesCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EventTypesCreateResponseObject); ok {
		if err := validResponse.VisitEventTypesCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EventTypesDelete operation middleware
func (sh *strictHandler) EventTypesDelete(w http.ResponseWriter, r *http.Request, eventTypeId string) {
	var request EventTypesDeleteRequestObject

	request.EventTypeId = eventTypeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EventTypesDelete(ctx, request.(EventTypesDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventTypesDelete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EventTypesDeleteResponseObject); ok {
		if err := validResponse.VisitEventTypesDeleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EventTypesGet operation middleware
func (sh *strictHandler) EventTypesGet(w http.ResponseWriter, r *http.Request, eventTypeId string) {
	var request EventTypesGetRequestObject

	request.EventTypeId = eventTypeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EventTypesGet(ctx, request.(EventTypesGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventTypesGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EventTypesGetResponseObject); ok {
		if err := validResponse.VisitEventTypesGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EventTypesUpdate operation middleware
func (sh *strictHandler) EventTypesUpdate(w http.ResponseWriter, r *http.Request, eventTypeId string) {
	var request EventTypesUpdateRequestObject

	request.EventTypeId = eventTypeId

	var body EventTypesUpdateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EventTypesUpdate(ctx, request.(EventTypesUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventTypesUpdate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EventTypesUpdateResponseObject); ok {
		if err := validResponse.VisitEventTypesUpdateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EventTypesListSlots operation middleware
func (sh *strictHandler) EventTypesListSlots(w http.ResponseWriter, r *http.Request, eventTypeId string) {
	var request EventTypesListSlotsRequestObject

	request.EventTypeId = eventTypeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EventTypesListSlots(ctx, request.(EventTypesListSlotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventTypesListSlots")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EventTypesListSlotsResponseObject); ok {
		if err := validResponse.VisitEventTypesListSlotsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GuestGet operation middleware
func (sh *strictHandler) GuestGet(w http.ResponseWriter, r *http.Request) {
	var request GuestGetRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GuestGet(ctx, request.(GuestGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GuestGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GuestGetResponseObject); ok {
		if err := validResponse.VisitGuestGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GuestCreate operation middleware
func (sh *strictHandler) GuestCreate(w http.ResponseWriter, r *http.Request) {
	var request GuestCreateRequestObject

	var body GuestCreateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GuestCreate(ctx, request.(GuestCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GuestCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GuestCreateResponseObject); ok {
		if err := validResponse.VisitGuestCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GuestUpdate operation middleware
func (sh *strictHandler) GuestUpdate(w http.ResponseWriter, r *http.Request) {
	var request GuestUpdateRequestObject

	var body GuestUpdateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GuestUpdate(ctx, request.(GuestUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GuestUpdate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GuestUpdateResponseObject); ok {
		if err := validResponse.VisitGuestUpdateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ScheduleGet operation middleware
func (sh *strictHandler) ScheduleGet(w http.ResponseWriter, r *http.Request) {
	var request ScheduleGetRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ScheduleGet(ctx, request.(ScheduleGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ScheduleGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ScheduleGetResponseObject); ok {
		if err := validResponse.VisitScheduleGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ScheduleUpdate operation middleware
func (sh *strictHandler) ScheduleUpdate(w http.ResponseWriter, r *http.Request) {
	var request ScheduleUpdateRequestObject

	var body ScheduleUpdateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ScheduleUpdate(ctx, request.(ScheduleUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ScheduleUpdate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ScheduleUpdateResponseObject); ok {
		if err := validResponse.VisitScheduleUpdateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FxfbxvXlf8qF7N9kHbHFB2rRUygD4rEOMLKpNek4i1MLzUmr8xpyBl2ZmjVNQSQVG0nsGtt3CwadLFJ",
	"nWKxD/tCyWLM6A8F9BPc+xXySRbnnMvhDGdIUZXk2Nm82Jo/uvfc8/d3/oweaiW7VrctbnmulnqouaUK",
	"rxn440LDq+QapRJ38bLM3ZJj1j3TtrSUJv4qW+JYdOWn4kg+Fd8xsSsfib7YSzHZEl3Zki3Rk9tw+6nY",
	"Ex35uWzLltxm8onoyqboites4nn1rFV9wEq2/YnJ2Zq9YXGn6HLXNW1rLaHpWt2x69zxTI4k2J/Av9xq",
	"1LTUbc9p8Du65j2ocy2l3bXtKjcsbXNT1xz+m4bp8LKWug2/MnzJvvtrXvK0TV37wCjf5L9pcNdLO47t",
	"wLLhrUp2mQc20z5eWFleWsgvZzPF9M2b2Zuari1mM/mFxXzxZvpfVpdvppc0XcutZPPF68u5hZXla5nh",
	"nexqvpj9sHhrObOUvRW4mVteShdzix+ll1ZX0gE6Xc8xrXtAZ427rnEPKRl5NnJOpHf4fuyZgcvWvRhZ",
	"fi6boi+ORA//3xUd+Fl0owIoOdzweHnBg4t126kZnpbSyobHL3lmDQiInIBbZfdU79/nlpfHuw+1nzl8",
	"XUtp/zA3VNI5paFz6jhp//1NXbsHEl20azVueTE8Uy+ka4ZZHf84Y9T4+Kc3KrYV/9gsh07ZaJjluAO6",
	"nuF4p2DJiKBx0SGTAuv5vA6eQw/IbIJSLOJLMarxBSoDmHiXiT1xABbcEn3xGowaVWabiZ04/ZHbUf3x",
	"6V4uR/cyy2zGrTbuzZLTgEVxb9EXr0SfybboiWPRof135FO4QZvES2p6PQjTgbcZ7Clbsi23E0x8JXbk",
	"tngtOrItuuJAdMURA3cHj+H4Txm4PtETR0zsAytkW3TEvmyn2FBpmOiJA9Fjw72Bdl8FOFKjn00pR6T3",
	"DVErfw80vbEjTVT5EQr/S3TkE9ERByDhFvwH++hsOZdl7/8ieZmt5hcTTPwZlEG2QRnY5Z8zcQiEyS2k",
	"6ZCJHhO7dC2bcNEX++JIdBicTxyLHgSjELOnt7egyoaMbSiWCXaVDnqzkaO/RC97CMSOU25Gp4B3DkFC",
	"sj3e2Jj4b2UxPRVq0US/BcM9BsGDkJncwrsob9xhsHPUWMsNxwBar5tWw6NbPv9My7vy3pB3puXxe9wZ",
	"esGICnimV50ijJHLxHf1CAFxfF60rfWqWZo2jC+t3lhZXlzIp4vpj9OZfDH/qxvp4rIfqD9Yzf3qwuPw",
	"JJ34BoQxqgTfN78A/e6JvYD0dTRL2RZ92SQAdiy3xA6Yo9iXW6ILurIrDkRH7Ckv8Bh+ZSB7wGTNOB9t",
	"3DfMqnHXrJreA7yuVrPrWur25Gh8i/NPqg9ypQovN6pc27yjR9UdztSSbbGLBIBf7zK065ayUYU7QHHJ",
	"UW2JY3gPf6uXYOI/UIt7YBZdMm6KQn3iUQ9X6osD+Uy8Jh6AIRSs+F0C3JHP5GOwtGNwQ1tocAfol8BI",
	"nrOZa+n83I3VPMPzwglnEyDK0BEjwvwqeiyKn+imaO3H4Ggx3IEggQQUNPzgizrWp8ZYZyR0H4AroOMN",
	"2CifwXZEQVc+Qc8ZcqfyEWiW7247BOfbYh+ENXDQfbHLZkJ+eDbkXgfuoWb81qyB5V1+P6lrNdNSVz8f",
	"7zlG0wzkHaotHII0vYdCO0Lz+D09JkNQAEL3dcNPOyLC7kLcOMZwEQY0qGhfwwPwubKZYgWg0rEvlYxq",
	"taAl6Fwr3LrnVbTUL67oWt3wPO4Avf9227j0u+Slq3f+aeaS/+PsP/4sToK+S4yGRPF6iMJ1plhOgOhb",
	"0Rno9TCgP4+SLP4E0sPQfRi0OuIgrN9HE9ynE53GLQfInc5JX0M4dgaIORcr8scgrCCqifiyU8G86cHY",
	"qeFW3EqWQnQja3wpDoOSjf9dh9d47S53rset8CfEPIAYCAo8C6xGgOJKEhh9JLriOzYzSL7xZEWzvIbc",
	"By/VRBzVF4fBX5gNEDQu6bYo8whQOVYrbjj2uhlrBqDPfZT1QegIesT+QRFkE/y9OFShUPSj1QX/gO+W",
	"nsS6xS/HesCArGfQjHYB3aEpASSQrSg/Zs9ZP+OchzUOKKMWrFqfWPaGNSWIu7aazuWLq5l/zmRvZS4c",
	"rq3Y90wrX3Fsz6vy8pQkrmSvLWeKC/l8+vqNfK6Y/tfFdHopvXThxGZs70O7YU1LZgAEZ7L54ofZ1czF",
	"05jdsLiDXJ0uGAwqiwSORiBb1JarY1b+T6wjYD4bWUUPgEnEZ2hOPaxVtsQ+RJkBVMBnTYBVhIyaEFgh",
	"MscaUd1w3Q3biTPhr2EdAqtvjqIRaRGvAmTGyStXtb3Y9BUgxA5KhlDFAB6i4IDToo+FYXUdA0Un1HRG",
	"CkenrCKescgWramNY4x7k7t123LjXOVXhLrQ61J5I8yxQ8KequaBl5TvU/miHylfhHniwvZTCGaI2yHX",
	"gNCIL7ympAi3pixncGrYyvR4zT2pBIuaselzxnAc4wFcb5hW2d5IW2U3a8VqvqpGIKbogY5QNHsWX7lh",
	"M5fnffyhA/X74kA+h/yMsGIXwhGedlt+SkvORso9cWpChObw3GNIRXsiVDGZSMhAw7SwmdX84jSEjGjf",
	"CFUj/NSV4OM0Mm/W+LLlcee+UY2N3YAYyEN0xAEm35h4PiGywdU2AUVRdWikqIZn0lFFyfdQssGSV1PJ",
	"5PfNP16+kkomY003hpQ/Y/qBNYlemCrwfYCMZFMcgtNjH32UqtUSTHwBzlJ8i5VK8hUgix1yofJTCBhH",
	"fjWxE2L7RDdxQlVySvpO3i7Ox5CDiZXlqmU0vIrtmL+bGnUsZ7BNVVy8mV5KZ/LLCys5Tdcy2WL2ViZ9",
	"s5hL53LL2YtHTCO1oDj2dgexbkIZCHPaLfRQGEcO0V21RA8iyqhQ+mKXakC+kR7hJsM6UlccRZVz3TFj",
	"U49tLH70BghjKm8YMr4Yr1izxzhDReqAHz2xf257ukZs6MZK4Q7FnfPbqxF3vhfo7Pex3NQi2VBn8Vz2",
	"9CqNmD3/BytWhIJend9ejThdfkF51znLbYOXY+XWRE05L5mNmHYNCzpwTCKA2KujkZAqkZCjNg8rmda6",
	"HaX5b/+r6hE92SKr7ISqT387oMC5hSGlLz+Tn/tVKh/N9mRrbN8jErMQ4ByibvfwtUNWMqqJkl1LFKyC",
	"Jf6CYaSXKliXmHhxYoGcvEqXWmHRQtpxsEoRV3ek3hm88EpuoZt7DM4teDwC60jPH31ojNsGzqxK+kEo",
	"t4NTFHj6V8jftr9+L1GwxL+LXaWcPWz0qXoZhN12iiGhVL/FhALi57CaJrqIerpM/gF5cSz65HOxMSjb",
	"YNEYgp+ymesf35gl3n6NiGIXu4IKHh2hL1UlfDauOUfS+CoG96ZYGPxRiO/h/wD+4vBfl9Bah8hDEIbr",
	"v1SV7E6okp0KdxSJ80dBBOCLATsTCEKO6L4CIfuT2pODvVVuhLCJ2jMqTZJbbG2kjLp2qh44C1KGjdzH",
	"qNE9Kt8VLFUP7MrPkCnPVEk8CABB/oioW/Ipk39A1iAkRLbSGf4S+3aKnbm9Em6tMCR9R/QLljrnVF2j",
	"ccyZWQu2tNZmdYahCPtIkRZSnyS7q9Jrsh5EGm3RJS5QToDRDIGzOu5ASbpUXyeMDByHN/opP7XbUzuQ",
	"16KSbFe1rIKVb9KsPTh3yCD0gjVs7KpyeRNbBkfyqXw0YAMAoiAjxHdE/Quge2gdiPKHpByr4Sx4/Nxv",
	"nQy78WJXNeTjVSGIy+j4bfJdwcVgAb+d4Nerx8QHTdfuc8elYJJMJBNJCGN2nVtG3dRS2hW8hS2YCkbD",
	"OUDNc34RqG67XmzUxpLSWCVFRPlKGSdFlUG1xu+1MACnyLFH2Fj3c+kOrkrBB+x8pBJdsEYH3QYLoiZQ",
	"PCBZKt2kC9DP+eRlthYD89cSyvuquhB6b8iJqKNFFnWImtyhCIBzAPLJYCNQmGPUlL7Yp63eu8rWxtQx",
	"sYQOOBp91nJZS+G04IoqJzk0WveBXX5AaYrlqUEco16vmiX8rblfuwSICauchGQCVcPNMHDxnAbHG1SI",
	"QS14L5k8t52Dc5C4dViX8hXO1IFZxXCZC6/yMi8DjyrcKHMHScpx79IiKgBchcnXA6SMpl+w43zy8rkd",
	"J5pXxhxqAY/LTJc1Aq9jz3v+vavnRktcbT2GmsWqyS2P8cHzTV2bu0sDNtS+4d6YBlJX7FECKbflZ2E/",
	"jY4PfPgEl8lmBjUxVmgkk1f4LwlufEcOD0LJlPW0sLGo6SB3xXQ97YyqO1UeMJj9jKYAp9Hnt0oT4dUx",
	"3v1lOIbuxI+3shm/i/VsNsHCRZ+/A+fpCmepdpuatRhWcwM4lsJutCI8rKGP1xnVR78YLxseB53K0V4+",
	"781PpZTMsMrMYBbfYA537YZT4vjCXc4tpkZfmeEyAx43qp5S4vOLDqOT5GOId7lznzusZDeqZWbZHmtY",
	"EBg8IN8LHK7c4MyzmWndN6pmmbkPLM/4rSJ6/tyIDrcJTyDZsIDedTNMKS/7DFfknV9YCA/1naAOJfWy",
	"yzZMr4IklhqOAwHD9QyPM3sdb9JxEoP4gXOdl8AZTgghLxXoBkx0crRIMPFl/ARaMK0ejKtGxpGiJu9P",
	"Cr65QBEapz9LqJjaPRM7RzuALDANHqipREYadSb2hnOPWI///vELNp+8OomdF+pDAyx8s/5zZOOfPGjE",
	"g75FKPrddZdzDwMz8Ztk31UeO9r3VzVs3ptk6eKl3JKf4TdjbbGLtYIIVA8UpEJlHvmIKmRye1BhABR2",
	"BM4Zq5eqKRuCg8Fyy8x8cn52kqdYoqPpWt1wjBr3MJm7/VAz4Xx1w6sMZptSI18KTJ/g3Ym4hPkoK/MV",
	"7nDQJMtmSmlAy11uldm67TCvYroDGevsbsNDIar0k9WMB+wuZw2XrzeqCfb2GcNbDG1ghTEJJgb6Lflk",
	"kn5ThmiWJynZNe69YQ1L/sBB590Qe73hxY7175CHOcGtoXqILiAZgIrqMysmeuIVjkA1h20dcFyTFGS1",
	"rgZHLlhHfnAw9Jbo5U/g5sfszyfimTl/rG5cSjhhum7yZ3xxY32h2bbZRMEaNgqPVScG8p1Xw68+Au2r",
	"UPrZHen6sWDTb5iIjm/6UaevYPnfVx0PG13YFx+sgU3XWMyGI4wKtcltuDwpqcUZync2+IUnQH9sARDs",
	"BD8SmFxjj/tIQ9XFe9jKIy2haeDoxxhMfI5zDOqJ+qJYtgioR1YoWOpFaofNs7XQ5wAxnSn8woAg1oUp",
	"Quhblh9UD6LfU5wXGJqimDMX/2kOVd1HPkXyu55rw++EfgnGvBZVkoIV/Tsikz5Swm+EaITDzwHV3yTB",
	"hBKHR3zNC3/fLjpKtZJjVOlCi0fBHd5w+ejv1uHTV5DOsTH6/7ySf3HmPlXuE55/A2Tjf3Q6mB8KGryy",
	"NxrZ7dEoTFxQGDj3gjWdd/fzowszyZBdvLks5qxx5SfruAjrAGDkBsbb47HRNwCbCSaP/UMHU8/IRRV/",
	"MF9/wchm9A87vOMDA42xhbzhZ2nyOaVoaqSYijwXJb4LdV1xwntzzuvsqvNTHeZM+g4v04koq45Ad3/+",
	"XI2Q+qWBttgXPU3XGk5VS2kVz6un5uaqdsmoVmzXS72ffD85Z9RNbfPO5v8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
